### 차원변경

In [2]:
'''
    차원 증가 (1차원 -> 2차원)
    [10 20 30] (3,) --> [[10 20 30]] (1,3)
                        [[10][20][30]] (3,1)
                        
    1) arr1D.reshape(1,-1)
    2) np.reshape(arr1D,(1,-1))
    3) np.expand_dims(arr1D,axis=0)
    4) arr1D[np.newaxis,...] (권장)
       arr1D[np.newaxis,:]
                        
                        
'''

'\n    차원 증가 (1차원 -> 2차원)\n    [10 20 30] (3,) --> [[10 20 30]] (1,3)\n                        [[10][20][30]] (3,1)\n                        \n    1) arr1D.reshape(1,-1)\n                        \n                        \n'

In [3]:
import numpy as np

### 1) arr1D.reshape(1,-1)

In [5]:
arr1D = np.array([10,20,30])
arr2D = arr1D.reshape(1,-1)
arr1D.shape, arr2D.shape

((3,), (1, 3))

### 2) np.reshape(arr1D,(1,-1))

In [6]:
arr1D = np.array([10,20,30])
arr2D = np.reshape(arr1D,(1,-1))
arr1D.shape, arr2D.shape

((3,), (1, 3))

### 3) np.expand_dims(arr1D,axis=0)

In [7]:
arr1D = np.array([10,20,30])
arr2D = np.expand_dims(arr1D,axis=0)
arr1D.shape,arr2D.shape

((3,), (1, 3))

### 4) arr1D[np.newaxis,...] 또는 arr1D[np.newaxis,:]

In [9]:
arr1D = np.array([10,20,30])
#arr2D = arr1D[np.newaxis,...]
arr2D = arr1D[np.newaxis,:]
arr1D.shape,arr2D.shape

((3,), (1, 3))

In [10]:
'''
    차원 증가 (1차원 -> 2차원)
    [10 20 30] (3,) --> [[10][20][30]] (3,1)
                        
    1) arr1D.reshape(-1,1)
    2) np.reshape(arr1D,(-1,1))
    3) np.expand_dims(arr1D,axis=1)
    4) arr1D[...,np.newaxis] (권장)
       arr1D[:,np.newaxis]
                        
                        
'''

'\n    차원 증가 (1차원 -> 2차원)\n    [10 20 30] (3,) --> [[10][20][30]] (3,1)\n                        \n    1) arr1D.reshape(-1,1)\n    2) np.reshape(arr1D,(-1,1))\n    3) np.expand_dims(arr1D,axis=1)\n    4) arr1D[...,np.newaxis] (권장)\n       arr1D[:,np.newaxis]\n                        \n                        \n'

In [12]:
arr1D = np.array([10,20,30])
arr2D = arr1D.reshape(-1,1)
arr2D = np.reshape(arr1D,(-1,1))
arr2D = np.expand_dims(arr1D,axis=1)
arr2D = arr1D[...,np.newaxis]
arr1D.shape, arr2D.shape

((3,), (3, 1))

In [ ]:
'''
    차원 축소 (2차원 --> 1차원)
    [[10 20 30]] (1,3) --> [10 20 30] (3,)
                        
    arr1D = np.squeeze(arr2D, axis=0)                      
                        
'''

In [14]:
arr2D = np.array([[10,20,30]])
arr1D = np.squeeze(arr2D, axis=0)
arr2D.shape,arr1D.shape

((1, 3), (3,))

In [15]:
arr2D

array([[10, 20, 30]])

In [16]:
arr1D

array([10, 20, 30])

In [17]:
'''
    차원 축소 (2차원 --> 1차원)
    [[10] [20] [30]] (1,3) --> [10 20 30] (3,)
                        
    arr1D = np.squeeze(arr2D, axis=1)

                        
'''

'\n    차원 축소 (2차원 --> 1차원)\n    [[10 20 30]] (1,3) --> [10 20 30] (3,)\n                        \n    arr1D = np.squeeze(arr2D, axis=1)\n    2) np.reshape(arr1D,(-1,1))\n    3) np.expand_dims(arr1D,axis=1)\n    4) arr1D[...,np.newaxis] (권장)\n       arr1D[:,np.newaxis]\n                        \n                        \n'

In [18]:
arr2D = np.array([[10],[20],[30]])
arr1D = np.squeeze(arr2D, axis=1)
arr2D.shape,arr1D.shape

((3, 1), (3,))

In [20]:
arr2D

array([[10],
       [20],
       [30]])

In [21]:
arr1D

array([10, 20, 30])

### 3차원 --> 2차원

In [39]:
arr3D = np.arange(16).reshape(1,4,4)#1행 4열짜리가 4개
arr3D, arr3D.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]]),
 (1, 4, 4))

In [40]:
arr2D = np.squeeze(arr3D, axis=0)
arr3D,arr3D.shape,arr2D.shape

(array([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]]),
 (1, 4, 4),
 (4, 4))

In [41]:
arr3D = np.arange(16).reshape(4,4,1)
arr2D = np.squeeze(arr3D, axis=2)
arr3D,arr3D.shape,arr2D.shape

(array([[[ 0],
         [ 1],
         [ 2],
         [ 3]],
 
        [[ 4],
         [ 5],
         [ 6],
         [ 7]],
 
        [[ 8],
         [ 9],
         [10],
         [11]],
 
        [[12],
         [13],
         [14],
         [15]]]),
 (4, 4, 1),
 (4, 4))

In [42]:
arr3D = np.arange(16).reshape(4,1,4)
arr2D = np.squeeze(arr3D, axis=1)
arr3D,arr3D.shape,arr2D.shape

(array([[[ 0,  1,  2,  3]],
 
        [[ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15]]]),
 (4, 1, 4),
 (4, 4))

In [43]:
'''
    다차원 --> 1차원
    
    1.arrND.flatten() ==> 복사본 (깊은 복사)
    2.arrND.ravel()   ==> 얕은복사
    
'''

'\n    다차원 --> 1차원\n    \n    1.arrND.flatten() ==> 복사본 (깊은 복사)\n    2.arrND.ravel()   ==> 얕은복사\n    \n'

In [45]:
arr2D = np.array([[10],[20],[30]])

In [46]:
arr2D.flatten()

array([10, 20, 30])

In [49]:
arr3D = np.arange(16).reshape(4,1,4)
arr3D,arr3D.flatten()

(array([[[ 0,  1,  2,  3]],
 
        [[ 4,  5,  6,  7]],
 
        [[ 8,  9, 10, 11]],
 
        [[12, 13, 14, 15]]]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]))