In [1]:
'''

    PCA 
    
    - 4개의 피쳐를 모두 사용했을 때의 교차검증해서 score 값 확인
    - 2개의 피쳐로 차원 축소 후 교차검증해서 score 값 확인
    

'''

'\n\n    PCA \n    \n    - 4개의 피쳐를 모두 사용했을 때의 교차검증해서 score 값 확인\n    - 2개의 피쳐로 차원 축소 후 교차검증해서 score 값 확인\n    \n\n'

In [2]:
import pandas as pd
import numpy as np

### 1. 데이터 준비

In [4]:
from sklearn.datasets import load_iris

In [5]:
iris = load_iris()

In [6]:
iris_data = iris.data
iris_target = iris.target

### 2. 표준화

In [7]:
from sklearn.preprocessing  import StandardScaler

In [8]:
sc = StandardScaler()
sc.fit(iris_data)
iris_data_scaled = sc.transform(iris_data)

In [10]:
iris_data_scaled.shape # 원본은 4개의 피쳐

(150, 4)

### 3. 모델 생성

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
rfc = RandomForestClassifier(random_state=1)

### 가. 차원 축소 전 교차검증 정확도

In [13]:
from sklearn.model_selection import cross_val_score

In [14]:
val_scores = cross_val_score(rfc,
                             iris_data_scaled,
                             iris_target, 
                             cv=5, 
                             scoring="accuracy")
val_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

In [15]:
np.mean(val_scores)

0.9666666666666668

### 나. 차원축소후 교차검증 정확도

In [16]:
from sklearn.decomposition import PCA

In [17]:
pca = PCA(n_components=2)
pca.fit(iris_data_scaled)
iris_pca = pca.transform(iris_data_scaled)

In [19]:
iris_pca.shape  # 4개의 피쳐를 2개로 차원축소함

(150, 2)

In [20]:
val_scores = cross_val_score(rfc,
                             iris_pca,
                             iris_target, 
                             cv=5, 
                             scoring="accuracy")
val_scores

array([0.83333333, 0.93333333, 0.83333333, 0.9       , 1.        ])

In [21]:
np.mean(val_scores)

0.9

In [22]:
'''
결론은 원본보다 pca 검증 score가  96%에서 90%정도 낮아졌지만 
4개의 속성이 2개로 (50% 정도 감소)감소한 것을 고려하면 PCA가 원본 데이터의 대표성(원본데이터의 고유한 특성)을 상당부분 유지된것으로 
확인할 수 있다.
'''

'\n결론은 원본보다 pca 검증 score가  96%에서 90%정도 낮아졌지만 \n4개의 속성이 2개로 (50% 정도 감소)감소한 것을 고려하면 PCA가 원본 데이터의 대표성(원본데이터의 고유한 특성)을 상당부분 유지된것으로 \n확인할 수 있다.\n'

### 변동성 비율 ==> PCA가 원본 데이터의 대표성을 얼마나 잘 나타내는지를 수치화

In [24]:
pca.explained_variance_ratio_

array([0.72962445, 0.22850762])

In [25]:
'''
  PCA(2개의 피쳐)가 원본데이터의 분산정도를 95% 정도 대변할 수 있다.
'''

'\n  PCA(2개의 피쳐)가 원본데이터의 분산정도를 95% 정도 대변할 수 있다.\n'

In [26]:
### 원본 데이터로 변경
pca.inverse_transform(iris_pca).shape

(150, 4)